# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RudderSample' do
  # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    source 'https://github.com/CocoaPods/Specs.git'

    pod 'Alamofire', '~> 5.0.0-beta.5'
    pod 'RxCocoa', '~> 5'
    pod 'RxSwift', '~> 5'

  # Pods for RudderSample

  target 'RudderSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RudderSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
